
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rmili
 */
public class gymManagement extends javax.swing.JFrame {

    /**
     * Creates new form gymManagement
     */
    public gymManagement() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dbCheck = new javax.swing.JCheckBox();
        bbCheck = new javax.swing.JCheckBox();
        ellCheck = new javax.swing.JCheckBox();
        trdmCheck = new javax.swing.JCheckBox();
        sqrCheck = new javax.swing.JCheckBox();
        kettleCheck = new javax.swing.JCheckBox();
        dbQty = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bbQty = new javax.swing.JTextField();
        trdmQty = new javax.swing.JTextField();
        ellQty = new javax.swing.JTextField();
        sqrQty = new javax.swing.JTextField();
        kettleQty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalQty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Milith's Gym Equipment");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dbCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dbCheck.setText("Dumbbells");
        dbCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbCheckActionPerformed(evt);
            }
        });

        bbCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbCheck.setText("Barbells");
        bbCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbCheckActionPerformed(evt);
            }
        });

        ellCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ellCheck.setText("Ellipticals");
        ellCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellCheckActionPerformed(evt);
            }
        });

        trdmCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        trdmCheck.setText("Treadmills");
        trdmCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trdmCheckActionPerformed(evt);
            }
        });

        sqrCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sqrCheck.setText("Squat Racks");
        sqrCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrCheckActionPerformed(evt);
            }
        });

        kettleCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kettleCheck.setText("Kettlebells");
        kettleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kettleCheckActionPerformed(evt);
            }
        });

        dbQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");

        bbQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        trdmQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        ellQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        sqrQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        kettleQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbCheck)
                    .addComponent(sqrCheck)
                    .addComponent(kettleCheck)
                    .addComponent(ellCheck)
                    .addComponent(trdmCheck)
                    .addComponent(bbCheck))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbQty)
                    .addComponent(trdmQty)
                    .addComponent(ellQty)
                    .addComponent(kettleQty)
                    .addComponent(sqrQty)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dbQty)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbCheck)
                    .addComponent(dbQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bbCheck)
                    .addComponent(bbQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trdmCheck)
                    .addComponent(trdmQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ellCheck)
                    .addComponent(ellQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kettleCheck)
                    .addComponent(kettleQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrCheck)
                    .addComponent(sqrQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalQty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalQty, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dbCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbCheckActionPerformed

    private void bbCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbCheckActionPerformed

    private void ellCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ellCheckActionPerformed

    private void trdmCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trdmCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trdmCheckActionPerformed

    private void sqrCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrCheckActionPerformed

    private void kettleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kettleCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kettleCheckActionPerformed

    
    
    DefaultTableModel m;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int sum = 0;
        if(dbCheck.isSelected())
        {
            String dumbbell = "Dumbbells";
            int  price = 250;
            int  qty = Integer.parseInt(dbQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                dumbbell,
                price,
                qty,
                tot
            }        
             );    
        }
        
        if(bbCheck.isSelected())
        {
            String barbell = "Barbells";
            int  price = 300;
            int  qty = Integer.parseInt(bbQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                barbell,
                price,
                qty,
                tot
            }        
             ); 
            }
        
         if(trdmCheck.isSelected())
        {
            String treadmill = "Treadmills";
            int  price = 5000;
            int  qty = Integer.parseInt(trdmQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                treadmill,
                price,
                qty,
                tot
            }        
             );    
        }
        
        if(ellCheck.isSelected())
        {
            String elliptical = "Ellipticals";
            int  price = 3000;
            int  qty = Integer.parseInt(ellQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                elliptical,
                price,
                qty,
                tot
            }        
         );    
        }
        
         if(kettleCheck.isSelected())
        {
            String kettlebell = "Kettlebells";
            int  price = 60;
            int  qty = Integer.parseInt(kettleQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                kettlebell,
                price,
                qty,
                tot
            }        
         );    
        }
         
         
          if(sqrCheck.isSelected())
        {
            String squatRack = "Knock Out";
            int  price = 4000;
            int  qty = Integer.parseInt(sqrQty.getText());
            int tot = price * qty;  
            m = (DefaultTableModel)jTable1.getModel();
            
            m.addRow(new Object[]          
            {
                squatRack,
                price,
                qty,
                tot
            }        
         );    
        }
        
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());  
        }
        
        totalQty.setText(Integer.toString(sum));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gymManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gymManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gymManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gymManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gymManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bbCheck;
    private javax.swing.JTextField bbQty;
    private javax.swing.JCheckBox dbCheck;
    private javax.swing.JTextField dbQty;
    private javax.swing.JCheckBox ellCheck;
    private javax.swing.JTextField ellQty;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox kettleCheck;
    private javax.swing.JTextField kettleQty;
    private javax.swing.JCheckBox sqrCheck;
    private javax.swing.JTextField sqrQty;
    private javax.swing.JTextField totalQty;
    private javax.swing.JCheckBox trdmCheck;
    private javax.swing.JTextField trdmQty;
    // End of variables declaration//GEN-END:variables
}
